export const OPERATIONS = {
    ADDITION: '+',
    DIVISION: '÷',
    MULTIPLY: '×',
    SUBTRACT: '-'
}

export const ACTIONS = {
    ADD_DECIMAL: 'ADD_DECIMAL',
    ADD_INPUT_VALUE: 'ADD_INPUT_VALUE',
    CHANGE_OPERATION: 'CHANGE_OPERATION',
    CALCULATE_RESULT: 'CALCULATE_RESULT'
}